Repository WOTCStrategyOverhaul/CovertInfiltration, pull requests merged in 2019-02, with the labels that each got.

#93 Schedule for non-abandoned/non-lost ambushes
  CovertInfiltration/Config/XComMissionDefs.ini
  CovertInfiltration/Config/XComSchedules.ini
Labels: gameplay, help wanted

#91 Add MissionSources and proper RewardDeck system
  CovertInfiltration/Config/XComInfiltration.ini
  CovertInfiltration/Config/XComMissionSources.ini
  CovertInfiltration/CovertInfiltration.x2proj
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Localization/XComGame.int
  CovertInfiltration/Src/CovertInfiltration/Classes/CI_XComGameState_CovertAction.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIMission_Infiltrated.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertMissionInfo_DefaultMissions.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Item_InfiltrationQuestItems.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationActions.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationMissionSources.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_PhaseOneActionsSpawner.uc
Labels: gameplay

#107 Make setup of infil missions more configurable
  CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertMissionInfoTemplate.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2CovertMissionInfo_DefaultMissions.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
Labels: action spawning, enhancement
