Repository WOTCStrategyOverhaul/CovertInfiltration, pull requests merged in 2020-04, with the labels that each got.

#489 Split off ASR
  CovertInfiltration/Config/XComGame.ini
  CovertInfiltration/CovertInfiltration.x2proj
  CovertInfiltration/Src/CovertInfiltration/Classes/UIBetterSitRepDetails.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIBetterSitRepDetails_Row.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_SitRepInformation.uc
Labels: organizational

#503 Prevent random negative and positive sitreps from spawning on retaliations
  CovertInfiltration/Config/XComInfiltration.ini
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
Labels: bug, gameplay

#471 Activity system overhaul to create semi-randomized chains
  CovertInfiltration/Config/XComGameBoard.ini
  CovertInfiltration/Config/XComGameData.ini
  CovertInfiltration/Config/XComInfiltration.ini
  CovertInfiltration/Config/XComMissionSources.ini
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Localization/XComGame.int
  CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UICovertActionsGeoscape.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityChainTemplate.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_CovertAction.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationModTemplate.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivityChains.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultComplications.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChain.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChainSpawner.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
Labels: feature, gameplay

#508 Show an activity's place in its chain on the covert ops list
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
Labels: enhancement, ui/ux

#504 Rebalance chain spawner values and show obfuscated spawn rate to player
  CovertInfiltration/Config/XComInfiltration.ini
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Src/CovertInfiltration/Classes/UIChainsOverview.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_InfiltrationTutorial.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_ActivityChainSpawner.uc
Labels: enhancement, gameplay
