Repository WOTCStrategyOverhaul/CovertInfiltration, pull requests merged in 2020-03, with the labels that each got.

#462 Overhaul X2InfiltrationModTemplate system and rebalance infiltration values
  CovertInfiltration/Config/XComInfiltration.ini
  CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationMod.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationModTemplate.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2InfiltrationModTemplateManager.uc
Labels: enhancement, feature, mod compatibility

#470 Disallow free promotion from spawning as a CA slot reward
  CovertInfiltration/Config/XComGameData.ini
  CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
Labels: bug, gameplay

#473 Cleanup missionsites when activities expire
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Assault.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2ActivityTemplate_Mission.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Assault.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Infiltration.uc
Labels: bug

#485 Split off Prototype Armoury
  CovertInfiltration/Config/XComContent.ini
  CovertInfiltration/Config/XComGame.ini
  CovertInfiltration/Config/XComGameBoard.ini
  CovertInfiltration/Config/XComGameCore.ini
  CovertInfiltration/Config/XComModConfigMenu_Defaults.ini
  CovertInfiltration/Config/XComStrategyTuning.ini
  CovertInfiltration/Config/XComWeaponTuning.ini
  CovertInfiltration/CovertInfiltration.x2proj
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Localization/XComGame.int
  CovertInfiltration/Src/CovertInfiltration/Classes/CI_DataStructures.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/ModConfigMenu_Defaults.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIDropWeaponUpgradeButton.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_ModConfigMenu.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_SSManageEquipment.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_WeaponUpgrade.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Item_InfiltrationArmors.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationPointsOfInterest.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationRewards.uc
Labels: organizational

#486 Split off Living Space
  CovertInfiltration/Config/XComGame.ini
  CovertInfiltration/Config/XComInfiltration.ini
  CovertInfiltration/Config/XComUI.ini
  CovertInfiltration/CovertInfiltration.x2proj
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Localization/XComGame.int
  CovertInfiltration/Src/CovertInfiltration/Classes/UIAlert_CovertInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration_UI.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationFacilityUpgrades.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertInfiltrationInfo.uc
Labels: organizational
