Repository WOTCStrategyOverhaul/CovertInfiltration, pull requests merged in 2021-03, with the labels that each got.

#641 Increase difficulty of assault missions
  CovertInfiltration/Config/XComGameBoard.ini
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
Labels: design, gameplay

#590 Ensure a scanning site spawns if none are available
  CovertInfiltration/Config/XComGameData.ini
Labels: bug, config only

#642 MCM rework
  CovertInfiltration/Config/XComCovertInfiltration_DEFAULT.ini
  CovertInfiltration/Config/XComModConfigMenu_Defaults.ini
  CovertInfiltration/CovertInfiltration.x2proj
  CovertInfiltration/Localization/CovertInfiltration.int
  CovertInfiltration/Src/CovertInfiltration/Classes/CI_MCMDefaults.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/CI_MCMScreen.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/ModConfigMenu_Defaults.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_CovertActionListItem_CI.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIEventQueue_ListItem_CI.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_MCM.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIListener_ModConfigMenu.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UISSManager_CovertAction.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/UIUtilities_InfiltrationTutorial.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Encyclopedia_InfiltrationTutorialClosure.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2EventListener_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_Activity_Assault.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_CovertActionExpirationManager.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/XComGameState_MissionSiteInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/MCM_API_CfgHelpersStatic.uci
  CovertInfiltration/Src/ModConfigMenuAPI/Classes/MCM_OptionsScreen.uc
  CovertInfiltration/Src/ModConfigMenuAPI/MCM_API_CfgHelpers.uci
  CovertInfiltration/Src/ModConfigMenuAPI/MCM_API_Includes.uci
Labels: on hold

#646 Prevent the tech rush covert action from spawning
  CovertInfiltration/Config/XComGameBoard.ini
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationActions.uc
Labels: gameplay

#647 Revisit covert action variety for B3.4
  CovertInfiltration/Config/XComGameBoard.ini
  CovertInfiltration/Src/CovertInfiltration/Classes/X2DownloadableContentInfo_CovertInfiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2Helper_Infiltration_TemplateMod.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_DefaultActivities.uc
  CovertInfiltration/Src/CovertInfiltration/Classes/X2StrategyElement_InfiltrationActions.uc
Labels: gameplay
